### PR TITLE
Rojo resturcure & updated the system

### PR DESCRIPTION
**Pull request by ccuser44**

### CODE REVIEW

**Comment by ccuser44** [comment]
Ok didn't fully check if this works properly so please verify that ROJO works.

Also when I was testing it I discovered that your endpoint returned notscams and scams as null

**Comment by jack-hags** [comment]
hm. im investigating the problem with the system now

**Comment by jack-hags** [comment]
I think its a brain.js issue, since the old version is having the same problem, and that hasn't been touched since it was working

**Comment by jack-hags** [comment]
nevermind. we just need more training data, sometimes it doesn't have enough to run

**Pull request merged**
