### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by ccuser44**

### CODE REVIEW

**Comment by jack-hags** [comment]
Still unfinished

**Comment by ccuser44** [comment]
Ok done.
Notable changes:
Hashlib was removed as hashing the messages isn't necessary.
By default messages will not be filtered in studio. If you want to debug set IS_DEBUG to true.

**Comment by jack-hags** [comment]
Looks good. I’ll accept it when I get back on my computer again.

**Comment by jack-hags** [comment]
Also, we don’t need the HashLib script anymore, right?

**Comment by ccuser44** [comment]
Yeah. I removed it in the pull request.

**Comment by ccuser44** [comment]
Will the pull be merged in the future?

**Review by ChrisvanChip — APPROVED** [review]
Looks good, not recognized any faulty syntax nor common issues.

**Comment by jack-hags** [comment]
Hey sorry for the delay.

The project is active again now.


I'll merge this and keep working.


Thanks for all your help!

**Pull request merged**
